### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ajurkow** [jkonno/AOG_full_CAN_Teensy_40#1]
Which tractor uses this PVEA-CI?
Regards

**Comment by jkonno** [comment]
Don't know to be honest, the code works with every CAN valve using the ISOBUS standard hydraulics messages, should also work with PVED-CC etc.

**Comment by ajurkow** [comment]
Ok, but when I see in your code:
 uint32_t wasMessageID = 0x018FF0B15;
  uint32_t steerSwID = 0x018EFFF21;
  uint32_t pressureMessageID = 0x018FF034E;
  uint32_t flowCommandID = 0x0CFE3022;

These frames id's are for specific tractor manufacture or are standard for all?

**Comment by jkonno** [comment]
It's for the sensor specified in the readme file.
